Preferences.addAll([
    { id: "extensions.createjiraissue.jiraurl", type: "string",  instantApply: "true" },
    { id: "extensions.createjiraissue.username", type: "unichar",  instantApply: "true" },
    { id: "extensions.createjiraissue.password", type: "unichar", instantApply: "false" },
    { id: "extensions.createjiraissue.rest", type: "bool",  instantApply: "true" },
    { id: "extensions.createjiraissue.projectmapping", type: "string",  instantApply: "false" },
    { id: "extensions.createjiraissue.addheader", type: "bool",  instantApply: "true" },
    { id: "extensions.createjiraissue.addheadertype", type: "string",  instantApply: "true" },
    { id: "extensions.createjiraissue.assigntome", type: "bool",  instantApply: "true" },
    { id: "extensions.createjiraissue.preferredcommenttab", type: "int",  instantApply: "true" },
    { id: "extensions.createjiraissue.tempDirDefault", type: "bool",  instantApply: "true" },
    { id: "extensions.createjiraissue.tempDirAlternate", type: "string",  instantApply: "true" },
    { id: "extensions.createjiraissue.keepTempFiles", type: "bool",  instantApply: "true" },
    { id: "extensions.createjiraissue.addOnTempoSupport", type: "bool",  instantApply: "true" },
    { id: "extensions.createjiraissue.language", type: "string",  instantApply: "true" },
    { id: "extensions.createjiraissue.decimalsep", type: "string",  instantApply: "true" },
    { id: "extensions.createjiraissue.replyHeaderCreate", type: "unichar",  instantApply: "true" },
    { id: "extensions.createjiraissue.replyBodyCreate", type: "unichar",  instantApply: "true" },
    { id: "extensions.createjiraissue.replyHeaderComment", type: "unichar",  instantApply: "true" },
    { id: "extensions.createjiraissue.replyBodyComment", type: "unichar",  instantApply: "true" },
    { id: "extensions.createjiraissue.replyCC", type: "string",  instantApply: "true" },
    { id: "extensions.createjiraissue.wizard", type: "bool",  instantApply: "true" },
]);