divOne.addEventListener('click', function () {
          browser.myapi.setSixteen();
          browser.myapi.setOne('calendarDisplayDeck', 'width', '50%');
          browser.myapi.setTwo('calendarContent', 'appendChild', 'taskContainer');
          browser.myapi.setThree('calendar-task-box', 'display', 'flex');
          browser.myapi.setFour('calendar-task-tree', 'height', '3%');
          browser.myapi.setFive('calendar-task-tree', 'flex', '1');
          browser.myapi.setSix('calendar-task-box', 'flexWrap', 'none');
          browser.myapi.setOne('task-addition-box', 'width', '100%');
          browser.myapi.setSeven('task-addition-box', 'height', '5%');
          browser.myapi.setSeven('calendar-task-details-container', 'height', '35%');
          browser.myapi.setSeven('calendar-task-tree', 'height', '55%');
          browser.myapi.setEight('calendar-task-tree', 'flex', '1');
          browser.myapi.setEight('calendar-task-details-container', 'flex', '1');
          browser.myapi.setTwo('calendar-task-box', 'appendChild', 'taskContainer');
          browser.myapi.setNine('calendar-task-tree', 'resize', 'vertical');
          browser.myapi.setTen('calendar-task-tree', 'overflow', 'auto'); 
          browser.myapi.setEleven('calendar-task-box', 'flexDirection', 'column');
          browser.myapi.setFifteen('calendar-task-box', 'insertBefore', 'calendar-task-details-container', 'task-addition-box');
          browser.myapi.setFourteen('calendar-task-tree', 'refresh', 'true');
          browser.myapi.setSeventeen();
          browser.myapi.setEighteen();
});

divTwo.addEventListener('click', function () {
          browser.myapi.setSixteen();
          browser.myapi.setOne('calendarDisplayDeck', 'width', '50%');
          browser.myapi.setTwo('calendarContent', 'appendChild', 'taskContainer');
          browser.myapi.setThree('calendar-task-box', 'display', 'flex');
          browser.myapi.setFour('calendar-task-tree', 'height', '3%');
          browser.myapi.setFive('calendar-task-tree', 'flex', '1');
          browser.myapi.setSix('calendar-task-box', 'flexWrap', 'none');
          browser.myapi.setOne('task-addition-box', 'width', '100%');
          browser.myapi.setSeven('task-addition-box', 'height', '5%');
          browser.myapi.setSeven('calendar-task-details-container', 'height', '35%');
          browser.myapi.setSeven('calendar-task-tree', 'height', '55%');
          browser.myapi.setEight('calendar-task-tree', 'flex', '1');
          browser.myapi.setEight('calendar-task-details-container', 'flex', '1');
          browser.myapi.setTwo('calendar-task-box', 'appendChild', 'taskContainer');
          browser.myapi.setNine('calendar-task-tree', 'resize', 'vertical');
          browser.myapi.setTen('calendar-task-tree', 'overflow', 'auto'); 
          browser.myapi.setEleven('calendar-task-box', 'flexDirection', 'column');
          browser.myapi.setOne('calendarDisplayDeck', 'width', '');
          browser.myapi.setThree('calendar-task-box', 'display', '');
          browser.myapi.setFour('calendar-task-tree', 'height', '');
          browser.myapi.setFive('calendar-task-tree', 'flex', '');
          browser.myapi.setSix('calendar-task-box', 'flexWrap', '');
          browser.myapi.setOne('task-addition-box', 'width', '');
          browser.myapi.setSeven('task-addition-box', 'height', '');
          browser.myapi.setSeven('calendar-task-details-container', 'height', '');
          browser.myapi.setSeven('calendar-task-tree', 'height', '');
          browser.myapi.setEight('calendar-task-tree', 'flex', '');
          browser.myapi.setEight('calendar-task-details-container', 'flex', '');
          browser.myapi.setNine('calendar-task-tree', 'resize', 'vertical');
          browser.myapi.setTen('calendar-task-tree', 'overflow', 'auto'); 
          browser.myapi.setEleven('calendar-task-box', 'flexDirection', '');
          browser.myapi.setFourteen('calendar-task-tree', 'refresh', 'true');
          browser.myapi.setSeventeen();
          browser.myapi.setEighteen();
});

divThree.addEventListener('click', function () {
          browser.myapi.setSixteen();
          browser.myapi.setOne('calendarDisplayDeck', 'width', '50%');
          browser.myapi.setTwo('calendarContent', 'appendChild', 'taskContainer');
          browser.myapi.setThree('calendar-task-box', 'display', 'flex');
          browser.myapi.setFour('calendar-task-tree', 'height', '3%');
          browser.myapi.setThree('calendar-task-tree', 'display', 'internal');
          browser.myapi.setThirteen('calendar-task-tree', 'display', 'table-column');
          browser.myapi.setEleven('calendar-task-box', 'flexDirection', 'row');
          browser.myapi.setSix('calendar-task-box', 'flexWrap', 'wrap');
          browser.myapi.setOne('task-addition-box', 'width', '100%');
          browser.myapi.setTwo('calendar-task-box', 'appendChild', 'taskContainer');
          browser.myapi.setSeven('task-addition-box', 'height', '5%');
          browser.myapi.setSeven('calendar-task-details-container', 'height', '95%');
          browser.myapi.setSeven('calendar-task-tree', 'height', '95%');
          browser.myapi.setEight('calendar-task-tree', 'flex', '1');
          browser.myapi.setEight('calendar-task-details-container', 'flex', '1');
          browser.myapi.setNine('calendar-task-tree', 'resize', 'horizontal');
          browser.myapi.setTen('calendar-task-tree', 'overflow', 'auto');
          browser.myapi.setFourteen('calendar-task-tree', 'refresh', 'true');
          browser.myapi.setSeventeen();
          browser.myapi.setEighteen();
});