pref("extensions.findnow.export.overwrite", true);
pref("extensions.findnow.export.set_filetime", false);
pref("extensions.findnow.exportEML.use_dir", false);
pref("extensions.findnow.log.enable", false);
pref("extensions.findnow.export.filename_charset", "");
pref("extensions.findnow.delay.clean_statusbar", 5000);
pref("extensions.findnow.export.filenames_toascii", true);
pref("extensions.findnow.export.filenames_addtime", true);
pref("extensions.findnow.exportEML.filename_format", 2);
pref("extensions.findnow.export.cut_subject", true);
pref("extensions.findnow.export.cut_filename", true);
pref("extensions.findnow.export.filename_add_prefix", false);
pref("extensions.findnow.export.filename_useisodate", true);
pref("extensions.findnow.export.save_auto_eml", false);
pref("extensions.findnow.export.filename_pattern", "%d %s-%k");
pref("extensions.findnow.export.charset_list", "ARMSCII-8,GEOSTD8,ISO-8859-1,ISO-8859-2,ISO-8859-3,ISO-8859-4,ISO-8859-5,ISO-8859-6,ISO-8859-7,ISO-8859-8,ISO-8859-9,ISO-8859-10,ISO-8859-11,ISO-8859-12,ISO-8859-13,ISO-8859-14,ISO-8859-15,ISO-8859-16,KOI8-R,KOI8-U,UTF-8,UTF-8 (BOM),WINDOWS-1250,WINDOWS-1251,WINDOWS-1252,WINDOWS-1253,WINDOWS-1254,WINDOWS-1255,WINDOWS-1256,WINDOWS-1257,WINDOWS-1258");
pref("extensions.findnow.button.show_default", false);
pref("extensions.findnow.exportEML.use_sub_dir", false);