var { ExtensionCommon } = ChromeUtils.import("resource://gre/modules/ExtensionCommon.jsm");

var { Services } = ChromeUtils.import("resource://gre/modules/Services.jsm");

var { ExtensionParent } = ChromeUtils.import("resource://gre/modules/ExtensionParent.jsm");

var extension = ExtensionParent.GlobalManager.getExtension("FrameWhite@Sungho.Hwang");

var w322 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#tabmail-tabs').style.setProperty('background-color', 'black', 'important');
var w305 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#tabmail-tabs').style.setProperty('color', 'white', 'important');
var w323 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#tabmail-tabs').style.setProperty('filter', 'invert(100%) brightness(130%)', 'important');
var w232 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('mail-toolbox').style.setProperty('background-color', 'white', 'important');
var w233 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('mail-toolbox').style.setProperty('color', 'black', 'important');
var w234 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-toolbox').style.setProperty('background-color', 'white', 'important');
var w235 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-toolbox').style.setProperty('color', 'black', 'important');
var w236 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-toolbox').style.setProperty('background-color', 'white', 'important');
var w237 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-toolbox').style.setProperty('color', 'black', 'important');
var w238 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-addition-box').style.setProperty('background-color', 'white', 'important');
var w239 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-addition-box').style.setProperty('color', 'black', 'important');
var w142 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-tabbox').style.setProperty('background-color', 'white', 'important');
var w143 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-nav-control').style.setProperty('background-color', 'white', 'important');
var w144 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-nav-control').style.setProperty('color', 'black', 'important');
var w145 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-deck').style.setProperty('background-color', 'white', 'important');
var w146 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-deck').style.setProperty('color', 'black', 'important');
var w147 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-view-box').style.setProperty('background-color', 'white', 'important'); 
var w148 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-view-box').style.setProperty('color', 'black', 'important');
var w149 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-view-splitter').style.setProperty('background-color', 'white', 'important');
var w150 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('threadTree').style.setProperty('color', 'black', 'important');
var w151 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('agenda-panel').style.setProperty('background-color', 'white', 'important');
var w152 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('agenda-panel').style.setProperty('color', 'black', 'important');
var w153 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('today-pane-panel').style.setProperty('background-color', 'white', 'important');
var w154 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('today-pane-panel').style.setProperty('color', 'black', 'important');
var w155 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('todaypane-new-event-button').style.setProperty('background-color', 'white', 'important');
var w156 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('todaypane-new-event-button').style.setProperty('color', 'black', 'important');
var w160 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('status-bar').style.setProperty('background-color', 'white', 'important');
var w161 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('status-bar').style.setProperty('color', 'black', 'important');
var w162 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('status-bar').style.setProperty('border-color', 'ThreeDShadow', 'important');
var w163 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('status-bar').style.setProperty('border-top', 'solid', 'important');
var w164 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('status-bar').style.setProperty('border-top-width', '1px', 'important');
var w165 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('status-bar').style.setProperty('border-top-color', 'ThreeDShadow', 'important');
var w166 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('quick-filter-bar').style.setProperty('background-color', 'white', 'important');
var w167 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('quick-filter-bar').style.setProperty('color', 'black', 'important');
var w168 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-add-task-button').style.setProperty('border-color', 'ThreeDShadow', 'important');
var w169 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-add-task-button').style.setProperty('background-color', 'white', 'important');
var w170 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-add-task-button').style.setProperty('color', 'black', 'important');
var w171 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-addition-box').style.setProperty('background-color', 'white', 'important');
var w172 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-addition-box').style.setProperty('color', 'black', 'important');
var w173 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-searchBox').style.setProperty('background-color', 'white', 'important');
var w174 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-searchBox').style.setProperty('color', 'black', 'important');
var w175 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('attachmentBar').style.setProperty('background-color', 'white', 'important');
var w176 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('attachmentBar').style.setProperty('color', 'black', 'important');
var w177 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details-grid').style.setProperty('color', 'black', 'important');
var w178 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('navigation-toolbox').style.setProperty('background-color', 'white', 'important');
var w179 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('navigation-toolbox').style.setProperty('color', 'black', 'important');
var w180 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-tree').style.setProperty('background-color', 'white', 'important');
var w181 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-tree').style.setProperty('color', 'black', 'important');
var w182 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('messengerBox').style.setProperty('background-color', 'white', 'important');
var w183 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('messengerBox').style.setProperty('color', 'black', 'important');
var w184 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderUnreadCol').style.setProperty('background-color', 'white', 'important');
var w185 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderUnreadCol').style.setProperty('color', 'black', 'important');
var w186 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderTotalCol').style.setProperty('background-color', 'white', 'important');
var w187 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderTotalCol').style.setProperty('color', 'black', 'important');
var w188 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderSizeCol').style.setProperty('background-color', 'white', 'important');
var w189 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderSizeCol').style.setProperty('color', 'black', 'important');
var w190 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-search-results-tree').style.setProperty('background-color', 'white', 'important');
var w191 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-search-results-tree').style.setProperty('color', 'black', 'important');
var w194 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-tree').style.setProperty('background-color', 'white', 'important');
var w195 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-tree').style.setProperty('color', 'black', 'important');
var w196 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('ltnSidebar').style.setProperty('background-color', 'white', 'important');
var w197 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('ltnSidebar').style.setProperty('color', 'black', 'important');
var w198 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderPaneBox').style.setProperty('background-color', 'white', 'important');
var w199 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('folderPaneBox').style.setProperty('color', 'black', 'important');
var w200 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('agenda-toolbar').style.setProperty('background-color', 'white', 'important');
var w201 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('agenda-toolbar').style.setProperty('color', 'black', 'important');
var w202 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('agenda-listbox').style.setProperty('background-color', 'white', 'important');
var w203 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('agenda-listbox').style.setProperty('color', 'black', 'important');
var w204 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-tabbox').style.setProperty('background-color', 'white', 'important');
var w205 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-tabbox').style.setProperty('color', 'black', 'important');
var w206 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-task-edit-field').style.setProperty('background-color', 'white', 'important');
var w207 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-task-edit-field').style.setProperty('color', 'black', 'important');
var w208 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-task-edit-field').style.setProperty('background-color', 'white', 'important');
var w209 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('view-task-edit-field').style.setProperty('color', 'black', 'important');
var w210 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details').style.setProperty('background-color', 'white', 'important');
var w211 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details').style.setProperty('color', 'black', 'important');
var w212 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details-description').style.setProperty('background-color', 'white', 'important');
var w213 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details-description').style.setProperty('color', 'black', 'important');
var w214 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-todo-tree').style.setProperty('background-color', 'white', 'important');
var w215 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('unifinder-todo-tree').style.setProperty('color', 'black', 'important');
var w216 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-actions-toolbar').style.setProperty('background-color', 'white', 'important');
var w217 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-actions-toolbar').style.setProperty('color', 'black', 'important');
var w218 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('offline-status').style.setProperty('background-color', 'white', 'important');
var w219 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('offline-status').style.setProperty('color', 'black', 'important');
var w220 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('expandedHeadersTopBox').style.setProperty('background-color', 'white', 'important');
var w221 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('expandedHeadersTopBox').style.setProperty('color', 'black', 'important');
var w228 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('searchInput').style.setProperty('background-color', 'black', 'important');
var w229 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('searchInput').style.setProperty('color', 'black', 'important');
var w230 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('gloda-search').style.setProperty('background-color', 'black', 'important');
var w231 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('gloda-search').style.setProperty('color', 'black', 'important');
var w5 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-tree').style.setProperty('background-color', 'white', 'important');
var w6 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-tree').style.setProperty('color', 'black', 'important');
var w7 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details-container').style.setProperty('background-color', 'white', 'important');
var w8 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-task-details-container').style.setProperty('color', 'black', 'important');
var w13 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('tabbar-toolbar').style.setProperty('background-color', 'black', 'important');
var w14 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('tabbar-toolbar').style.setProperty('color', 'white', 'important');
var w15 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('messagepanebox').style.setProperty('background-color', 'white', 'important');
var w16 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('messagepanebox').style.setProperty('color', 'black', 'important');
var w17 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('titlebar-max').style.setProperty('filter', 'invert(1)', 'important');
var w18 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('titlebar-min').style.setProperty('filter', 'invert(1)', 'important');
var w19 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('titlebar-close').style.setProperty('filter', 'invert(1)', 'important');
var w20 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-newtask-button').style.setProperty('filter', 'invert(1)', 'important');
var w21 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-newevent-button').style.setProperty('filter', 'invert(1)', 'important');
var w22 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('todaypane-new-event-button').style.setProperty('background-color', 'white', 'important');
var w23 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('todaypane-new-event-button').style.setProperty('color', 'black', 'important');
var w24 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('todaypane-new-event-button').style.setProperty('background-color', 'white', 'important');
var w25 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('todaypane-new-event-button').style.setProperty('color', 'black', 'important');
var w26 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-newtask-button').style.setProperty('filter', 'invert(1)', 'important');
var w27 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-delete').style.setProperty('background-color', 'white', 'important');
var w28 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-delete').style.setProperty('color', 'black', 'important');
var w29 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-saveandclose').style.setProperty('background-color', 'white', 'important');
var w30 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-saveandclose').style.setProperty('color', 'black', 'important');
var w31 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-privacy').style.setProperty('background-color', 'white', 'important');
var w32 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-privacy').style.setProperty('color', 'black', 'important');
var w33 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-attendees').style.setProperty('background-color', 'white', 'important');
var w34 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-attendees').style.setProperty('color', 'black', 'important');
var w35 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-freebusy').style.setProperty('background-color', 'white', 'important');
var w36 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-freebusy').style.setProperty('color', 'black', 'important');
var w39 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-add-task-button').style.setProperty('background-color', 'white', 'important');
var w40 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-add-task-button').style.setProperty('color', 'black', 'important');
var w41 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-url').style.setProperty('background-color', 'white', 'important');
var w42 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-url').style.setProperty('color', 'black', 'important');
var w43 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_archive').style.setProperty('filter', 'invert(1)', 'important');
var w44 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_compact').style.setProperty('filter', 'invert(1)', 'important');
var w45 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_file').style.setProperty('filter', 'invert(1)', 'important');
var w46 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_followup').style.setProperty('filter', 'invert(1)', 'important');
var w47 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_forward').style.setProperty('filter', 'invert(1)', 'important');
var w48 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_getNewMessages').style.setProperty('filter', 'invert(1)', 'important');
var w49 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_goForward').style.setProperty('filter', 'invert(1)', 'important');
var w50 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_junk').style.setProperty('filter', 'invert(0.3)', 'important');
var w51 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_mark').style.setProperty('filter', 'invert(1)', 'important');
var w52 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_next').style.setProperty('filter', 'invert(1)', 'important');
var w53 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_nextMsg').style.setProperty('filter', 'invert(1)', 'important');
var w54 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_previous').style.setProperty('filter', 'invert(1)', 'important');
var w55 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_previousMsg').style.setProperty('filter', 'invert(1)', 'important');
var w56 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('msgHeaderView').style.setProperty('background-color', 'white', 'important');
var w57 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('msgHeaderView').style.setProperty('color', 'black', 'important');
var w58 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('msgHeaderView').style.setProperty('border-color', 'black', 'important');
var w59 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-getmsg').style.setProperty('filter', 'invert(1)', 'important');
var w60 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-newmsg').style.setProperty('filter', 'invert(1)', 'important');
var w62 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-address').style.setProperty('filter', 'invert(1)', 'important');
var w65 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrReplyButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w66 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrReplyToSenderButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w68 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrReplyAllButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w70 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrFollowupButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w71 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrReplyListButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w73 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrForwardButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w74 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrTrashButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w76 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-delete-button').style.setProperty('filter', 'invert(1)', 'important');
var w77 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-delete-button').style.setProperty('filter', 'invert(1)', 'important');
var w78 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-delete-task-button').style.setProperty('filter', 'invert(1)', 'important');
var w80 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('hdrJunkButton').style.setProperty('filter', 'invert(0.3)', 'important');
var w89 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-tag').style.setProperty('filter', 'invert(1)', 'important');
var w96 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-chat').style.setProperty('filter', 'invert(1)', 'important');
var w99 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('qfb-show-filter-bar').style.setProperty('filter', 'invert(1)', 'important');
var w103 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-appmenu').style.setProperty('filter', 'invert(1)', 'important');
var w116 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-add-buddy').style.setProperty('filter', 'invert(1)', 'important');
var w117 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-join-chat').style.setProperty('filter', 'invert(1)', 'important');
var w118 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-chat-accounts').style.setProperty('filter', 'invert(1)', 'important');
var w119 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-tab-button').style.setProperty('background-color', 'black', 'important');
var w121 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-tab-button').style.setProperty('background-color', 'black', 'important');
var w122 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-synchronize-button').style.setProperty('filter', 'invert(1)', 'important');
var w123 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-synchronize-button').style.setProperty('filter', 'invert(1)', 'important');
var w125 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-newevent-button').style.setProperty('filter', 'invert(1)', 'important');
var w129 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-edit-button').style.setProperty('filter', 'invert(1)', 'important');
var w130 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-edit-button').style.setProperty('filter', 'invert(1)', 'important');
var w133 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-actions-category').style.setProperty('filter', 'invert(1)', 'important');
var w134 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-actions-markcompleted').style.setProperty('filter', 'invert(1)', 'important');
var w135 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-priority').style.setProperty('filter', 'invert(1)', 'important');
var w136 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-actions-priority').style.setProperty('filter', 'invert(1)', 'important');
var w137 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-status').style.setProperty('filter', 'invert(1)', 'important');
var w244 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('tree>treechildren').style.setProperty('filter', 'invert(1)', 'important');
var w245 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('findbar,.mail-toolbox,.contentTabToolbox, #msgHeaderView').style.setProperty('background-color', 'white', 'important');
var w246 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('findbar,.mail-toolbox,.contentTabToolbox, #msgHeaderView').style.setProperty('color', 'black', 'important');
var w247 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel > *').style.setProperty('background-color', 'white', 'important');
var w248 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel > *').style.setProperty('color', 'black', 'important');
var w249 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#threadTree>treechildren').style.setProperty('filter', 'invert(1)', 'important');
var w250 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#threadTree>treechildren').style.setProperty('background-color', 'black', 'important');
var w251 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('.treecol-text').style.setProperty('background-color', 'white', 'important');
var w252 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('.treecol-text').style.setProperty('color', 'black', 'important');
var w253 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('tree>.calendar-task-treechildren').style.setProperty('filter', 'invert(1)', 'important');
var w254 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('tree>treechildren').style.setProperty('background-color', 'black', 'important');
var w255 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_getNewMessages').style.setProperty('color', 'white', 'important');
var w256 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_junk').style.setProperty('color', 'white', 'important');
var w257 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button_mark').style.setProperty('color', 'white', 'important');
var w258 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-newmsg').style.setProperty('color', 'white', 'important');
var w259 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-delete-button').style.setProperty('color', 'white', 'important');
var w260 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-delete-button').style.setProperty('color', 'white', 'important');
var w261 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-newtask-button').style.setProperty('color', 'white', 'important');
var w262 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-tag').style.setProperty('color', 'white', 'important');
var w263 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-chat').style.setProperty('color', 'white', 'important');
var w264 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-synchronize-button').style.setProperty('color', 'white', 'important');
var w265 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-synchronize-button').style.setProperty('color', 'white', 'important');
var w266 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-newevent-button').style.setProperty('color', 'white', 'important');
var w267 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-edit-button').style.setProperty('color', 'white', 'important');
var w268 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('task-edit-button').style.setProperty('color', 'white', 'important');
var w269 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-newevent-button').style.setProperty('color', 'white', 'important');
var w270 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('calendar-newtask-button').style.setProperty('color', 'white', 'important');
var w271 = Services.wm.getMostRecentWindow('mail:3pane').document.getElementById('button-address').style.setProperty('color', 'white', 'important');
var w272 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#threadCols').style.setProperty('background-color', 'white', 'important');
var w273 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#threadCols').style.setProperty('color', 'black', 'important');
var w274 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-search-field').style.setProperty('background-color', 'white', 'important');
var w275 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-search-field').style.setProperty('color', 'black', 'important');
var w276 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('search-textbox').style.setProperty('background-color', 'white', 'important');
var w277 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('search-textbox').style.setProperty('color', 'black', 'important');
var w284 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('.statusbarpanel>#calendar-status-todaypane-button').style.setProperty('color', 'black', 'important');
var w285 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel>vbox').style.setProperty('background-color', 'white', 'important');
var w286 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel>vbox').style.setProperty('color', 'black', 'important');
var w446 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#calendar-toolbox>toolbar>.button-appmenu').style.setProperty('filter', 'invert(1)', 'important');
var w447 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#task-toolbox>toolbar>.button-appmenu').style.setProperty('filter', 'invert(1)', 'important');
var w448 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('search-textbox#task-text-filter-field').style.setProperty('background-color', 'white', 'important');
var w449 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('search-textbox#task-text-filter-field').style.setProperty('color', 'black', 'important');
var w450 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('.mail-toolbox>toolbar>toolbaritem').style.setProperty('filter', 'invert(1)', 'important');
var w555 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#calendar-tab-button').style.setProperty('filter', 'invert(1)', 'important');
var w556 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#task-tab-button').style.setProperty('filter', 'invert(1)', 'important');
var w557 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#msgHeaderView').style.setProperty('border', 'solid', 'important');
var w558 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#msgHeaderView').style.setProperty('border-width', '2px', 'important');
var w559 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#msgHeaderView').style.setProperty('border-color', 'black', 'important');
var w560 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#mailContent>#messengerBox').style.setProperty('border', 'solid', 'important');
var w561 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#mailContent>#messengerBox').style.setProperty('border-width', '2px', 'important');
var w562 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#mailContent>#messengerBox').style.setProperty('border-color', 'black', 'important');
var w563 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel').style.setProperty('border', 'solid', 'important');
var w564 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel').style.setProperty('border-width', '2px', 'important');
var w565 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel').style.setProperty('border-color', 'black', 'important');
var w566 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#ltnSidebar').style.setProperty('border', 'solid', 'important');
var w567 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#ltnSidebar').style.setProperty('border-width', '2px', 'important');
var w568 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#ltnSidebar').style.setProperty('border-color', 'black', 'important');
var w569 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#calendarContent').style.setProperty('border', 'solid', 'important');
var w570 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#calendarContent').style.setProperty('border-width', '2px', 'important');
var w571 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#calendarContent').style.setProperty('border-color', 'black', 'important');
var w572 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#ltnSidebar>#calendar-panel>#calendar-list-pane>#calendar-list-inner-pane>richlistbox>richlistitem').style.setProperty('color', 'black', 'important');
var w701 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-search-results-tree>treechildren').style.setProperty('background-color', 'black', 'important');
var w702 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-search-results-tree>treechildren').style.setProperty('color', 'white', 'important');
var w703 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-search-results-tree>treechildren').style.setProperty('filter', 'invert(1)', 'important');
var w704 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#today-pane-panel>vbox>#todo-tab-panel>vbox>#calendar-task-tree-detail>.calendar-task-tree>.calendar-task-treechildren').style.setProperty('color', 'black', 'important');
var w705 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-todo-tree>treechildren').style.setProperty('background-color', 'black', 'important');
var w706 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-todo-tree>treechildren').style.setProperty('color', 'navy', 'important');
var w707 = Services.wm.getMostRecentWindow('mail:3pane').document.querySelector('#unifinder-todo-tree>treechildren').style.setProperty('filter', 'invert(1)', 'important');

var myapi = class extends ExtensionCommon.ExtensionAPI {
  getAPI(context) {
    return {
      myapi: {
      code: async function() { function white() {
w322;
w305;
w323;
w232;
w233;
w234;
w235;
w236;
w237;
w238;
w239;
w142;
w143;
w144;
w145;
w146;
w147;
w148;
w149;
w150;
w151;
w152;
w153;
w154;
w155;
w156;
w160;
w161;
w162;
w163;
w164;
w165;
w166;
w167;
w168;
w169;
w170;
w171;
w172;
w173;
w174;
w175;
w176;
w177;
w178;
w179;
w180;
w181;
w182;
w183;
w184;
w185;
w186;
w187;
w188;
w189;
w190;
w191;
w194;
w195;
w196;
w197;
w198;
w199;
w200;
w201;
w202;
w203;
w204;
w205;
w206;
w207;
w208;
w209;
w210;
w211;
w212;
w213;
w214;
w215;
w216;
w217;
w218;
w219;
w220;
w221;
w228;
w229;
w230;
w231;
w5;
w6;
w7;
w8;
w13;
w14;
w15;
w16;
w17;
w18;
w19;
w20;
w21;
w22;
w23;
w24;
w25;
w26;
w27;
w28;
w29;
w30;
w31;
w32;
w33;
w34;
w35;
w36;
w39;
w40;
w41;
w42;
w43;
w44;
w45;
w46;
w47;
w48;
w49;
w50;
w51;
w52;
w53;
w54;
w55;
w56;
w57;
w58;
w59;
w60;
w62;
w63;
w65;
w66;
w68;
w70;
w71;
w73;
w74;
w76;
w77;
w78;
w80;
w89;
w96;
w99;
w103;
w116;
w117;
w118;
w119;
w121;
w122;
w123;
w125;
w129;
w130;
w133;
w134;
w135;
w136;
w137;
w244;
w245;
w246;
w247;
w248;
w249;
w250;
w251;
w252;
w253;
w254;
w255;
w256;
w257;
w258;
w259;
w260;
w261;
w262;
w263;
w264;
w265;
w266;
w267;
w268;
w269;
w270;
w271;
w272;
w273;
w274;
w275;
w276;
w277;
w284;
w285;
w286;
w446;
w447;
w448;
w449;
w450
w555;
w556;
w557;
w558;
w559;
w560;
w561;
w562;
w563;
w564;
w565;
w566;
w567;
w568;
w569;
w570;
w571;
w572;
w701;
w702;
w703;
w704;
w705;
w706;
w707;

   }
        }
      }
    }
  }
};