pref("extensions.quicknote.printfontsizeonevalue", 1);
pref("extensions.quicknote.printfontsize", 12);
pref("extensions.quicknote.firststart", true);
pref("extensions.quicknote.firststartmail", true);
pref("extensions.quicknote.firststartcmp", true);
pref("extensions.quicknote.lastVersion", "0");
pref("extensions.quicknote.autostart", false);
pref("extensions.quicknote.cursorposstart", false);
pref("extensions.quicknote.lasttabopen", 1);
pref("extensions.quicknote.numtabs", 2);
pref("extensions.quicknote.openqn", 1);
pref("extensions.quicknote.showUrl", true);
pref("extensions.quicknote.totabint", 1);
pref("extensions.quicknote.showclearbutton", false);
pref("extensions.quicknote.showprintbutton", false);
pref("extensions.quicknote.showsavebutton", false);
pref("extensions.quicknote.showsaveasbutton", false);
pref("extensions.quicknote.showinfirefoxbutton", true);
pref("extensions.quicknote.showinaddonsbar", false);
pref("extensions.quicknote.showqnbutton", true);
pref("extensions.quicknote.sendtext",false);
pref("extensions.quicknote.closestate",false);
pref("extensions.quicknote.senttext", "");
pref("extensions.quicknote.tab1path", "");
pref("extensions.quicknote.tab2path", "");
pref("extensions.quicknote.tab3path", "");
pref("extensions.quicknote.tab4path", "");
pref("extensions.quicknote.tab5path", "");
pref("extensions.quicknote.tab6path", "");
pref("extensions.quicknote.fontsize1", 12);
pref("extensions.quicknote.fontsize2", 12);
pref("extensions.quicknote.fontsize3", 12);
pref("extensions.quicknote.fontsize4", 12);
pref("extensions.quicknote.fontsize5", 12);
pref("extensions.quicknote.fontsize6", 12);
pref("extensions.quicknote.fontname1", "Verdana,sans-serif");
pref("extensions.quicknote.fontname2", "Verdana,sans-serif");
pref("extensions.quicknote.fontname3", "Verdana,sans-serif");
pref("extensions.quicknote.fontname4", "Verdana,sans-serif");
pref("extensions.quicknote.fontname5", "Verdana,sans-serif");
pref("extensions.quicknote.fontname6", "Verdana,sans-serif");
pref("extensions.quicknote.fontcolor1", "Black");
pref("extensions.quicknote.fontcolor2", "Black");
pref("extensions.quicknote.fontcolor3", "Black");
pref("extensions.quicknote.fontcolor4", "Black");
pref("extensions.quicknote.fontcolor5", "Black");
pref("extensions.quicknote.fontcolor6", "Black");
pref("extensions.quicknote.userstyle1", "background-image:none !important;");
pref("extensions.quicknote.userstyle2", "background-image:none !important;");
pref("extensions.quicknote.userstyle3", "background-image:none !important;");
pref("extensions.quicknote.userstyle4", "background-image:none !important;");
pref("extensions.quicknote.userstyle5", "background-image:none !important;");
pref("extensions.quicknote.userstyle6", "background-image:none !important;");
pref("extensions.quicknote.bgcolortab1", "#FFFF99");
pref("extensions.quicknote.bgcolortab2", "#FFFF99");
pref("extensions.quicknote.bgcolortab3", "#FFFF99");
pref("extensions.quicknote.bgcolortab4", "#FFFF99");
pref("extensions.quicknote.bgcolortab5", "#FFFF99");
pref("extensions.quicknote.bgcolortab6", "#FFFF99");
pref("extensions.quicknote.tab1name", "Note &1");
pref("extensions.quicknote.tab2name", "Note &2");
pref("extensions.quicknote.tab3name", "Note &3");
pref("extensions.quicknote.tab4name", "Note &4");
pref("extensions.quicknote.tab5name", "Note &5");
pref("extensions.quicknote.tab6name", "Note &6");
pref("extensions.quicknote.charset", "UTF-8");
pref("extensions.quicknote.autosave", 10);
pref("extensions.quicknote.dependent", false);
pref("extensions.quicknote.closechild", false);
pref("extensions.quicknote.tabBackground", false);