pref("changequote.headers.type",1);
pref("changequote.headers.english", false);
pref("changequote.headers.withcc",false);
pref("changequote.headers.date_long", false);
pref("changequote.headers.date_long_format", 0);
pref("changequote.replyformat.enable", false);
pref("changequote.replyformat.format", 0);
pref("changequote.news.reply_date_first", false);
pref("changequote.news.reply_header_locale","");
pref("changequote.news.reply_header_authorwrote", "%s");
pref("changequote.news.reply_header_ondate", "");
pref("changequote.news.reply_header_separator",", ");
pref("changequote.news.reply_header_colon", ":\n");
pref("changequote.reply.without_inline_images", false);
pref("changequote.window.close_after_reply", false);
pref("changequote.message.markread_after_reply", false);
pref("changequote.headers.customized", "");
pref("changequote.headers.news.customized", "");
pref("changequote.set.headers.news",false);
pref("changequote.headers.ignore_reply_to", false);
pref("changequote.headers.date_custom_format", "");
pref("changequote.headers.dateSender_custom_format", "");
pref("changequote.headers.add_newline", false);
pref("changequote.headers.capitalize_date", true);
pref("changequote.headers.label_bold", false);
pref("changequote.headers.custom_html_enabled", false);
pref("changequote.headers.custom_news_html_enabled", false);
