/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/.
 * Portions Copyright (C) Philipp Kewisch, 2012 */

#include "nsISupports.idl"

interface calIItemBase;

[scriptable, uuid(212bb466-fd98-413f-b4b4-89c68e9467af)]
interface calITrashcan : nsISupports
{
    void emptyTrash();


    void restoreItem(in calIItemBase aItem);
};
