pref("extensions.opacustep.sugarcrm_url", "");
pref("extensions.opacustep.sugarcrm_username", "");
pref("extensions.opacustep.sugarcrm_selectedmodules", "[\"Contacts\",\"Leads\",\"Accounts\"]");
pref("extensions.opacustep.sugarcrm_custom_modules", "[]");
pref("extensions.opacustep.opacusAB", "none");
pref("extensions.opacustep.opacusABLeads", "none");
pref("extensions.opacustep.tbirdLastSync", "0");
pref("extensions.opacustep.sugarcrmLastSync", "1970-01-01 00:00:00");
pref("extensions.opacustep.tbirdLastLeadSync", "0");
pref("extensions.opacustep.sugarcrmLastLeadSync", "1970-01-01 00:00:00");
pref("extensions.opacustep.opacus_notify",false);
pref("extensions.opacustep.opacus_cases",false);
pref("extensions.opacustep.opacus_addbcc",false);
pref("extensions.opacustep.auto_archive",false);
pref("extensions.opacustep.auto_archive_attachments",true);
pref("extensions.opacustep.opacus_ldap",false);
pref("extensions.opacustep.opacus_ldap_key","");
pref("extensions.opacustep.opacus_mycontactsonly",true);
pref("extensions.opacustep.opacus_honoursynctooutlook",false);
pref("extensions.opacustep.sugarcrmwins",true);
pref("extensions.opacustep.opacus_licence_key",'');
pref("extensions.opacustep.opacus_activation_key",'');
pref("extensions.opacustep.opacus_blacklist",'');
pref("extensions.opacustep.opacus_usestoredid",true);
pref("extensions.opacustep.opacus_searchonopen",true);
pref("extensions.opacustep.opacus_syncatstart",true);
pref("extensions.opacustep.opacus_synchourly",false);
pref("extensions.opacustep.opacus_syncmodules",'contacts');
pref("extensions.opacustep.delete_threshold",5);
pref("extensions.opacustep.opacus_syncdeletions",false);
pref("extensions.opacustep.filtersAfterSync",false);
pref("extensions.opacustep.opacusMailUniq",0);
pref("extensions.opacustep.ignoreConverted",true);
pref("extensions.opacustep.opacus_twowaysync",true);
pref("extensions.opacustep.firstrun",true);
pref("extensions.opacustep.version",'-1');
pref("extensions.opacustep.addButtons",true);
pref("extensions.opacustep.casePrefix","CASE:");

// See http://kb.mozillazine.org/Localize_extension_descriptions
pref("extensions.opacustep@opacus.co.uk.description", "chrome://opacustep/locale/opacustep.properties");
