// JavaScript

"use strict";

var suggest = {
    fr: new Map ([
        ["bcp", "beaucoup"],
        ["ca", "ça"],
        ["cad", "c’est-à-dire"],
        ["cb", "combien|CB"],
        ["cdlt", "cordialement"],
        ["construirent", "construire|construisirent|construisent|construiront"],
        ["càd", "c’est-à-dire"],
        ["chai", "j’sais|je sais"],
        ["chais", "j’sais|je sais"],
        ["chui", "j’suis|je suis"],
        ["chuis", "j’suis|je suis"],
        ["dc", "de|donc"],
        ["done", "donc|donne"],
        ["email", "courriel|e-mail|émail"],
        ["emails", "courriels|e-mails"],
        ["ete", "êtes|été"],
        ["Etes-vous", "Êtes-vous"],
        ["Etiez-vous", "Étiez-vous"],
        ["Etions-vous", "Étions-nous"],
        ["loins", "loin"],
        ["mn", "min"],
        ["mns", "min"],
        ["parce-que", "parce que"],
        ["pcq", "parce que"],
        ["pd", "pendant|pédé"],
        ["pdq", "pendant que"],
        ["pdt", "pendant"],
        ["pdtq", "pendant que"],
        ["pécunier", "pécuniaire"],
        ["pécuniers", "pécuniaires"],
        ["pk", "pourquoi"],
        ["pkoi", "pourquoi"],
        ["pq", "pourquoi|PQ"],
        ["prq", "presque"],
        ["prsq", "presque"],
        ["qcq", "quiconque"],
        ["qd", "quand"],
        ["qq", "quelque"],
        ["qqch", "quelque chose"],
        ["qqn", "quelqu’un"],
        ["qqne", "quelqu’une"],
        ["qqs", "quelques"],
        ["qqunes", "quelques-unes"],
        ["qquns", "quelques-uns"],
        ["tdq", "tandis que"],
        ["tj", "toujours"],
        ["tjs", "toujours"],
        ["tq", "tant que|tandis que"],
        ["ts", "tous"],
        ["tt", "tant|tout"],
        ["tte", "toute"],
        ["ttes", "toutes"],

        ["Iier", "Iᵉʳ"],
        ["Iière", "Iʳᵉ"],
        ["IIième", "IIᵉ"],
        ["IIIième", "IIIᵉ"],
        ["IVième", "IVᵉ"],
        ["Vième", "Vᵉ"],
        ["VIième", "VIᵉ"],
        ["VIIième", "VIIᵉ"],
        ["VIIIième", "VIIIᵉ"],
        ["IXième", "IXᵉ"],
        ["Xième", "Xᵉ"],
        ["XIième", "XIᵉ"],
        ["XIIième", "XIIᵉ"],
        ["XIIIième", "XIIIᵉ"],
        ["XIVième", "XIVᵉ"],
        ["XVième", "XVᵉ"],
        ["XVIième", "XVIᵉ"],
        ["XVIIième", "XVIIᵉ"],
        ["XVIIIième", "XVIIIᵉ"],
        ["XIXième", "XIXᵉ"],
        ["XXième", "XXᵉ"],
        ["XXIième", "XXIᵉ"],
        ["XXIIième", "XXIIᵉ"],
        ["XXIIIième", "XXIIIᵉ"],
        ["XXIVième", "XXIVᵉ"],
        ["XXVième", "XXVᵉ"],
        ["XXVIième", "XXVIᵉ"],
        ["XXVIIième", "XXVIIᵉ"],
        ["XXVIIIième", "XXVIIIᵉ"],
        ["XXIXième", "XXIXᵉ"],
        ["XXXième", "XXXᵉ"],
        ["Ier", "Iᵉʳ"],
        ["Ière", "Iʳᵉ"],
        ["IIème", "IIᵉ"],
        ["IIIème", "IIIᵉ"],
        ["IVème", "IVᵉ"],
        ["Vème", "Vᵉ"],
        ["VIème", "VIᵉ"],
        ["VIIème", "VIIᵉ"],
        ["VIIIème", "VIIIᵉ"],
        ["IXème", "IXᵉ"],
        ["Xème", "Xᵉ"],
        ["XIème", "XIᵉ"],
        ["XIIème", "XIIᵉ"],
        ["XIIIème", "XIIIᵉ"],
        ["XIVème", "XIVᵉ"],
        ["XVème", "XVᵉ"],
        ["XVIème", "XVIᵉ"],
        ["XVIIème", "XVIIᵉ"],
        ["XVIIIème", "XVIIIᵉ"],
        ["XIXème", "XIXᵉ"],
        ["XXème", "XXᵉ"],
        ["XXIème", "XXIᵉ"],
        ["XXIIème", "XXIIᵉ"],
        ["XXIIIème", "XXIIIᵉ"],
        ["XXIVème", "XXIVᵉ"],
        ["XXVème", "XXVᵉ"],
        ["XXVIème", "XXVIᵉ"],
        ["XXVIIème", "XXVIIᵉ"],
        ["XXVIIIème", "XXVIIIᵉ"],
        ["XXIXème", "XXIXᵉ"],
        ["XXXème", "XXXᵉ"]
    ])
};


if (typeof(exports) !== 'undefined') {
    exports.fr = suggest.fr;
}
